name: Build LaTex summary

on: [pull_request]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: true
      - name: build summary pdf
        uses: docker://texlive/texlive:latest
        with:
          args: latexmk -xelatex -cd -interaction=nonstopmode -file-line-error -jobname=main_summary -outdir=../build ./src/main_summary.tex
      - name: build cheatsheet pdf
        uses: docker://texlive/texlive:latest
        with:
          args: latexmk -xelatex -cd -interaction=nonstopmode -file-line-error -jobname=main_cheatsheet -outdir=../build ./src/main_cheatsheet.tex
      - name: build main pdf
        uses: docker://texlive/texlive:latest
        with:
          args: latexmk -xelatex -cd -interaction=nonstopmode -file-line-error -jobname=main -outdir=../build ./src/main.tex
      - name: Archive pdf's as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: build/main.pdf
          retention-days: 5
